mathilde_jobeet_mathilde_job:
    resource: "@MathildeJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

mathilde_jobeet_homepage:
    pattern:  /
    defaults: { _controller: MathildeJobeetBundle:Job:index }

MathildeJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: MathildeJobeetBundle:Category:show, page: 1 }
