mathilde_jobeet_mathilde_job:
    resource: "@MathildeJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

mathilde_jobeet_homepage:
    pattern:  /
    defaults: { _controller: MathildeJobeetBundle:Job:index }
